15:21:02.760 Running build in Washington, D.C., USA (East) â€“ iad1
15:21:02.760 Build machine configuration: 2 cores, 8 GB
15:21:02.798 Cloning github.com/teo-lapa/app-hub-platform (Branch: main, Commit: 67451ee)
15:21:03.218 Cloning completed: 420.000ms
15:21:04.101 Restored build cache from previous deployment (3TDGvvCj75fBeFxMcjgrfQKkspPR)
15:21:04.558 Running "vercel build"
15:21:04.945 Vercel CLI 48.1.6
15:21:05.276 Running "install" command: `npm install`...
15:21:08.277 
15:21:08.278 up to date, audited 420 packages in 3s
15:21:08.279 
15:21:08.279 150 packages are looking for funding
15:21:08.279   run `npm fund` for details
15:21:08.342 
15:21:08.343 1 critical severity vulnerability
15:21:08.343 
15:21:08.344 To address all issues, run:
15:21:08.344   npm audit fix --force
15:21:08.344 
15:21:08.344 Run `npm audit` for details.
15:21:08.377 Detected Next.js version: 14.0.3
15:21:08.378 Running "npm run build"
15:21:08.490 
15:21:08.491 > app-hub-platform@1.0.0 build
15:21:08.491 > next build
15:21:08.491 
15:21:09.186    â–² Next.js 14.0.3
15:21:09.187 
15:21:09.187    Creating an optimized production build ...
15:21:15.709  âœ“ Compiled successfully
15:21:15.714    Linting and checking validity of types ...
15:21:19.904 Failed to compile.
15:21:19.905 
15:21:19.905 ./app/api/catalogo-lapa/products/route.ts:71:57
15:21:19.906 Type error: 'error' is of type 'unknown'.
15:21:19.906 
15:21:19.906 [0m [90m 69 |[39m         }[0m
15:21:19.906 [0m [90m 70 |[39m       } [36mcatch[39m (error) {[0m
15:21:19.906 [0m[31m[1m>[22m[39m[90m 71 |[39m         console[33m.[39mlog([32m`ðŸ’¥ Errore auth ${cred.username}:`[39m[33m,[39m error[33m.[39mmessage)[33m;[39m[0m
15:21:19.907 [0m [90m    |[39m                                                         [31m[1m^[22m[39m[0m
15:21:19.907 [0m [90m 72 |[39m       }[0m
15:21:19.907 [0m [90m 73 |[39m     }[0m
15:21:19.907 [0m [90m 74 |[39m[0m
15:21:19.972 Error: Command "npm run build" exited with 1